name: al-hq

services:
  al-hq:
    build: .
    container_name: al-hq
    restart: unless-stopped
    ports:
      - 127.0.0.1:3004:80
    networks:
      - main

networks:
  main:
    external: true
