export type Volunteer = {
    id: number;
    name: string;
    age: number;
    profession: string;
    department: string | null;
    experience: string | null;
    conditions: string | null;
    inspiration: string | null;
    negative: string | null;
    camping: string | null;
    previously_participated: string | null;
    event_dates: string | null;
    duration: string | null;
    quantity: number | null;
    email: string | null;
    phone: string;
    social: string | null;
    fb: string | null;
    lang: string | null;
    country: string | null;
    help_now: boolean;
    program_name: string | null;
    program_direction: string | null;
    program_description: string | null;
    program_example: string | null;
    raider: string | null;
    additional_info: string | null;
    created_at: string;
    deleted_at: string | null;
    form_type: "volunteer" | string;
    time: string | null;
};
